"""M2–M5: التكاملات والأسرار، التشغيلات والاستهلاك والميزانية، الفرص والأدلة، المسودات والاعتمادات،
المحادثات والبريد، تيليجرام، ومخطط sales_graph لحالة LangGraph

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-22 13:45:47.694919
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLES = (
    "daily_quotas",
    "digests",
    "inbound_events",
    "integration_secrets",
    "integrations",
    "runs",
    "telegram_callbacks",
    "telegram_link_codes",
    "budget_reservations",
    "run_events",
    "usage_ledger",
    "evidence",
    "opportunities",
    "contact_permissions",
    "conversations",
    "drafts",
    "manual_contacts",
    "approvals",
    "messages",
    "outbound_commands",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_contacts_workspace_id_id"), "contacts", ["workspace_id", "id"], schema="sales"
    )
    op.create_table(
        "daily_quotas",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("discovery_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("qualified_slots_reserved", sa.Integer(), server_default="0", nullable=False),
        sa.Column("qualified_slots_used", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["sales.workspaces.id"],
            name=op.f("fk_daily_quotas_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("workspace_id", "local_date", name=op.f("pk_daily_quotas")),
        schema="sales",
    )
    op.create_table(
        "digests",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column(
            "content",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("body_text", sa.Text(), server_default="", nullable=False),
        sa.Column("sent_telegram_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["sales.workspaces.id"],
            name=op.f("fk_digests_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_digests")),
        sa.UniqueConstraint(
            "workspace_id", "local_date", name=op.f("uq_digests_workspace_id_local_date")
        ),
        schema="sales",
    )
    op.create_table(
        "inbound_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("event_id", sa.String(length=200), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=20), server_default="received", nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["sales.workspaces.id"],
            name=op.f("fk_inbound_events_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inbound_events")),
        sa.UniqueConstraint(
            "provider", "event_id", name=op.f("uq_inbound_events_provider_event_id")
        ),
        schema="sales",
    )
    op.create_table(
        "integration_secrets",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=60), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["sales.workspaces.id"],
            name=op.f("fk_integration_secrets_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_secrets")),
        sa.UniqueConstraint(
            "workspace_id", "key", name=op.f("uq_integration_secrets_workspace_id_key")
        ),
        schema="sales",
    )
    op.create_table(
        "integrations",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "health",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "last_sync_cursor",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "type IN ('models', 'mail', 'telegram', 'search', 'operations')",
            name=op.f("ck_integrations_type"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["sales.workspaces.id"],
            name=op.f("fk_integrations_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integrations")),
        sa.UniqueConstraint("workspace_id", "type", name=op.f("uq_integrations_workspace_id_type")),
        schema="sales",
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), server_default="running", nullable=False),
        sa.Column("graph_thread_id", sa.String(length=100), nullable=True),
        sa.Column("opportunity_id", sa.UUID(), nullable=True),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column(
            "config_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "summary",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "kind IN ('discover', 'process_opportunity', 'process_reply', 'digest', 'mail_sync', 'connection_test')",
            name=op.f("ck_runs_kind"),
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'completed', 'waiting_approval', 'retry_scheduled', 'blocked_budget', 'blocked_policy', 'failed', 'canceled', 'skipped_configuration')",
            name=op.f("ck_runs_status"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["sales.workspaces.id"],
            name=op.f("fk_runs_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
        schema="sales",
    )
    op.create_index(
        op.f("ix_runs_workspace_id"),
        "runs",
        ["workspace_id", sa.literal_column("started_at DESC")],
        unique=False,
        schema="sales",
    )
    op.create_table(
        "telegram_callbacks",
        sa.Column("token", sa.String(length=40), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("draft_id", sa.UUID(), nullable=False),
        sa.Column("draft_revision", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=10), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=True),
        sa.Column("message_id", sa.BigInteger(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["sales.workspaces.id"],
            name=op.f("fk_telegram_callbacks_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("token", name=op.f("pk_telegram_callbacks")),
        schema="sales",
    )
    op.create_table(
        "telegram_link_codes",
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("auth_user_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["auth_user_id"],
            ["sales.user_profiles.auth_user_id"],
            name=op.f("fk_telegram_link_codes_auth_user_id_user_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["sales.workspaces.id"],
            name=op.f("fk_telegram_link_codes_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_telegram_link_codes")),
        schema="sales",
    )
    op.create_table(
        "budget_reservations",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("scope_key", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column("settled_amount", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("currency", sa.String(length=3), server_default="USD", nullable=False),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'settled', 'released')",
            name=op.f("ck_budget_reservations_status"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["sales.runs.id"],
            name=op.f("fk_budget_reservations_run_id_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["sales.workspaces.id"],
            name=op.f("fk_budget_reservations_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budget_reservations")),
        schema="sales",
    )
    op.create_index(
        op.f("ix_budget_reservations_workspace_id_status"),
        "budget_reservations",
        ["workspace_id", "status"],
        unique=False,
        schema="sales",
    )
    op.create_table(
        "run_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("step", sa.String(length=60), nullable=False),
        sa.Column("event_type", sa.String(length=30), nullable=False),
        sa.Column("sanitized_summary", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["sales.runs.id"],
            name=op.f("fk_run_events_run_id_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["sales.workspaces.id"],
            name=op.f("fk_run_events_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_events")),
        schema="sales",
    )
    op.create_index(
        op.f("ix_run_events_run_id_occurred_at"),
        "run_events",
        ["run_id", "occurred_at"],
        unique=False,
        schema="sales",
    )
    op.create_table(
        "usage_ledger",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("opportunity_id", sa.UUID(), nullable=True),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("kind", sa.String(length=20), server_default="model", nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=120), server_default="", nullable=False),
        sa.Column("role", sa.String(length=30), server_default="", nullable=False),
        sa.Column("input_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("request_count", sa.Integer(), server_default="1", nullable=False),
        sa.Column("pricing_version", sa.String(length=40), server_default="", nullable=False),
        sa.Column(
            "estimated_cost", sa.Numeric(precision=14, scale=6), server_default="0", nullable=False
        ),
        sa.Column("actual_cost", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("currency", sa.String(length=3), server_default="USD", nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('discovery', 'new_opportunity', 'followup', 'test')",
            name=op.f("ck_usage_ledger_category"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["sales.runs.id"],
            name=op.f("fk_usage_ledger_run_id_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["sales.workspaces.id"],
            name=op.f("fk_usage_ledger_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_ledger")),
        schema="sales",
    )
    op.create_index(
        op.f("ix_usage_ledger_workspace_id_occurred_at"),
        "usage_ledger",
        ["workspace_id", "occurred_at"],
        unique=False,
        schema="sales",
    )
    op.create_table(
        "evidence",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("url", sa.String(length=2000), nullable=True),
        sa.Column("fact_type", sa.String(length=30), nullable=False),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("permitted_excerpt", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "confidence_label", sa.String(length=20), server_default="observed", nullable=False
        ),
        sa.Column(
            "storage_policy", sa.String(length=20), server_default="extracted_only", nullable=False
        ),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id", "company_id"],
            ["sales.companies.workspace_id", "sales.companies.id"],
            name="fkw_evidence_company_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "source_id"],
            ["sales.sources.workspace_id", "sales.sources.id"],
            name="fkw_evidence_source_id",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["sales.workspaces.id"],
            name=op.f("fk_evidence_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_evidence_workspace_id_id")),
        schema="sales",
    )
    op.create_index(
        op.f("ix_evidence_company_id"), "evidence", ["company_id"], unique=False, schema="sales"
    )
    op.create_table(
        "opportunities",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("segment_id", sa.UUID(), nullable=True),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="discovered", nullable=False),
        sa.Column("preliminary_score", sa.Integer(), server_default="0", nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column(
            "score_breakdown",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "facts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "hypotheses",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "missing_info",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "evidence_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("selection_reason", sa.Text(), server_default="", nullable=False),
        sa.Column("disqualify_reason", sa.Text(), nullable=True),
        sa.Column("graph_thread_id", sa.String(length=100), nullable=True),
        sa.Column("discovered_run_id", sa.UUID(), nullable=True),
        sa.Column("next_action_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_contacted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_demo_data", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("status_changed_by", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('discovered', 'qualified', 'draft_ready', 'contacted', 'interested', 'meeting_proposed', 'not_interested', 'won', 'lost', 'archived', 'disqualified')",
            name=op.f("ck_opportunities_status"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "company_id"],
            ["sales.companies.workspace_id", "sales.companies.id"],
            name="fkw_opportunities_company_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "product_id"],
            ["sales.products.workspace_id", "sales.products.id"],
            name="fkw_opportunities_product_id",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "segment_id"],
            ["sales.segments.workspace_id", "sales.segments.id"],
            name="fkw_opportunities_segment_id",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["sales.workspaces.id"],
            name=op.f("fk_opportunities_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunities")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_opportunities_workspace_id_id")),
        schema="sales",
    )
    op.create_index(
        op.f("ix_opportunities_workspace_id_status_next_action_at"),
        "opportunities",
        ["workspace_id", "status", "next_action_at"],
        unique=False,
        schema="sales",
    )
    op.create_index(
        "uq_opportunities_active_pair",
        "opportunities",
        ["workspace_id", "company_id", "product_id"],
        unique=True,
        schema="sales",
        postgresql_where=sa.text(
            "status NOT IN ('not_interested','won','lost','archived','disqualified')"
        ),
    )
    op.create_table(
        "contact_permissions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("purpose", sa.String(length=30), server_default="sales_outreach", nullable=False),
        sa.Column("status", sa.String(length=16), server_default="unknown", nullable=False),
        sa.Column("basis_reference", sa.Text(), server_default="", nullable=False),
        sa.Column("confirmed_by", sa.String(length=100), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('unknown', 'allowed', 'disallowed')",
            name=op.f("ck_contact_permissions_status"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "contact_id"],
            ["sales.contacts.workspace_id", "sales.contacts.id"],
            name="fkw_contact_permissions_contact_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["sales.workspaces.id"],
            name=op.f("fk_contact_permissions_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_permissions")),
        sa.UniqueConstraint(
            "contact_id", "purpose", name=op.f("uq_contact_permissions_contact_id_purpose")
        ),
        schema="sales",
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("opportunity_id", sa.UUID(), nullable=True),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column("channel", sa.String(length=10), server_default="email", nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("mailbox", sa.String(length=320), nullable=True),
        sa.Column("provider_thread_id", sa.String(length=300), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="open", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "company_id"],
            ["sales.companies.workspace_id", "sales.companies.id"],
            name="fkw_conversations_company_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "opportunity_id"],
            ["sales.opportunities.workspace_id", "sales.opportunities.id"],
            name="fkw_conversations_opportunity_id",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["sales.workspaces.id"],
            name=op.f("fk_conversations_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_conversations_workspace_id_id")),
        schema="sales",
    )
    op.create_index(
        op.f("ix_conversations_workspace_id_company_id"),
        "conversations",
        ["workspace_id", "company_id"],
        unique=False,
        schema="sales",
    )
    op.create_table(
        "drafts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("opportunity_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("reply_to_message_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=20), server_default="first_contact", nullable=False),
        sa.Column("channel", sa.String(length=10), server_default="email", nullable=False),
        sa.Column("revision", sa.Integer(), server_default="1", nullable=False),
        sa.Column("recipient_contact_id", sa.UUID(), nullable=True),
        sa.Column(
            "recipient_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("subject", sa.Text(), server_default="", nullable=False),
        sa.Column("body", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "attachment_refs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("product_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="pending_review", nullable=False),
        sa.Column("defer_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "policy_findings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "model_meta",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("channel IN ('email', 'whatsapp')", name=op.f("ck_drafts_channel")),
        sa.CheckConstraint(
            "kind IN ('first_contact', 'reply', 'followup')", name=op.f("ck_drafts_kind")
        ),
        sa.CheckConstraint(
            "status IN ('pending_review', 'approved', 'rejected', 'deferred', 'stale', 'sent', 'canceled')",
            name=op.f("ck_drafts_status"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "opportunity_id"],
            ["sales.opportunities.workspace_id", "sales.opportunities.id"],
            name="fkw_drafts_opportunity_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["sales.workspaces.id"],
            name=op.f("fk_drafts_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_drafts")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_drafts_workspace_id_id")),
        schema="sales",
    )
    op.create_index(
        op.f("ix_drafts_workspace_id_status"),
        "drafts",
        ["workspace_id", "status"],
        unique=False,
        schema="sales",
    )
    op.create_table(
        "manual_contacts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("opportunity_id", sa.UUID(), nullable=False),
        sa.Column("draft_id", sa.UUID(), nullable=True),
        sa.Column("channel", sa.String(length=10), server_default="whatsapp", nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column("actor_id", sa.String(length=100), nullable=False),
        sa.Column("note", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "contacted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "opportunity_id"],
            ["sales.opportunities.workspace_id", "sales.opportunities.id"],
            name="fkw_manual_contacts_opportunity_id",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["sales.workspaces.id"],
            name=op.f("fk_manual_contacts_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manual_contacts")),
        schema="sales",
    )
    op.create_table(
        "approvals",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("draft_id", sa.UUID(), nullable=False),
        sa.Column("draft_revision", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.String(length=100), nullable=False),
        sa.Column("via", sa.String(length=10), server_default="web", nullable=False),
        sa.Column("decision", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=12), server_default="active", nullable=False),
        sa.Column("note", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "decided_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "decision IN ('approve', 'reject', 'defer')", name=op.f("ck_approvals_decision")
        ),
        sa.CheckConstraint(
            "status IN ('active', 'superseded', 'expired', 'consumed')",
            name=op.f("ck_approvals_status"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "draft_id"],
            ["sales.drafts.workspace_id", "sales.drafts.id"],
            name="fkw_approvals_draft_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["sales.workspaces.id"],
            name=op.f("fk_approvals_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
        schema="sales",
    )
    op.create_index(
        "uq_approvals_active_revision",
        "approvals",
        ["draft_id", "draft_revision"],
        unique=True,
        schema="sales",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("channel", sa.String(length=10), server_default="email", nullable=False),
        sa.Column("provider_message_id", sa.String(length=300), nullable=True),
        sa.Column("internet_message_id", sa.String(length=500), nullable=True),
        sa.Column("in_reply_to", sa.String(length=500), nullable=True),
        sa.Column("references", sa.Text(), server_default="", nullable=False),
        sa.Column("from_address", sa.String(length=320), nullable=True),
        sa.Column("to_address", sa.String(length=320), nullable=True),
        sa.Column("subject", sa.Text(), server_default="", nullable=False),
        sa.Column("body_text", sa.Text(), server_default="", nullable=False),
        sa.Column("classification", sa.String(length=20), nullable=True),
        sa.Column(
            "classification_detail",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("link_status", sa.String(length=20), server_default="linked", nullable=False),
        sa.Column(
            "candidate_opportunity_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "sent_or_received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "direction IN ('inbound', 'outbound')", name=op.f("ck_messages_direction")
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["sales.conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["sales.workspaces.id"],
            name=op.f("fk_messages_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_messages_workspace_id_id")),
        schema="sales",
    )
    op.create_index(
        op.f("ix_messages_conversation_id_created_at"),
        "messages",
        ["conversation_id", "created_at"],
        unique=False,
        schema="sales",
    )
    op.create_index(
        "uq_messages_internet_id",
        "messages",
        ["workspace_id", "internet_message_id"],
        unique=True,
        schema="sales",
        postgresql_where=sa.text("internet_message_id IS NOT NULL"),
    )
    op.create_table(
        "outbound_commands",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("draft_id", sa.UUID(), nullable=False),
        sa.Column("draft_revision", sa.Integer(), nullable=False),
        sa.Column("approval_id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("channel", sa.String(length=10), server_default="email", nullable=False),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=True),
        sa.Column("internet_message_id", sa.String(length=500), nullable=True),
        sa.Column("provider_message_id", sa.String(length=300), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("reconciliation_needed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("resolved_by", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'sending', 'sent', 'unknown_delivery', 'failed', 'canceled')",
            name=op.f("ck_outbound_commands_status"),
        ),
        sa.ForeignKeyConstraint(
            ["approval_id"],
            ["sales.approvals.id"],
            name=op.f("fk_outbound_commands_approval_id_approvals"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "draft_id"],
            ["sales.drafts.workspace_id", "sales.drafts.id"],
            name="fkw_outbound_commands_draft_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["sales.workspaces.id"],
            name=op.f("fk_outbound_commands_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbound_commands")),
        sa.UniqueConstraint(
            "draft_id", "draft_revision", name=op.f("uq_outbound_commands_draft_id_draft_revision")
        ),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_outbound_commands_idempotency_key")),
        schema="sales",
    )
    op.create_index(
        op.f("ix_outbound_commands_workspace_id_status"),
        "outbound_commands",
        ["workspace_id", "status"],
        unique=False,
        schema="sales",
    )
    for table in TABLES:
        op.execute(f"ALTER TABLE sales.{table} ENABLE ROW LEVEL SECURITY")
    # حالة LangGraph في مخطط مستقل داخل القاعدة نفسها؛ الجداول ينشئها checkpointer.setup().
    op.execute("CREATE SCHEMA IF NOT EXISTS sales_graph")
    op.execute("REVOKE ALL ON SCHEMA sales_graph FROM PUBLIC")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP SCHEMA IF EXISTS sales_graph CASCADE")
    op.drop_index(
        op.f("ix_outbound_commands_workspace_id_status"),
        table_name="outbound_commands",
        schema="sales",
    )
    op.drop_table("outbound_commands", schema="sales")
    op.drop_index(
        "uq_messages_internet_id",
        table_name="messages",
        schema="sales",
        postgresql_where=sa.text("internet_message_id IS NOT NULL"),
    )
    op.drop_index(
        op.f("ix_messages_conversation_id_created_at"), table_name="messages", schema="sales"
    )
    op.drop_table("messages", schema="sales")
    op.drop_index(
        "uq_approvals_active_revision",
        table_name="approvals",
        schema="sales",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("approvals", schema="sales")
    op.drop_table("manual_contacts", schema="sales")
    op.drop_index(op.f("ix_drafts_workspace_id_status"), table_name="drafts", schema="sales")
    op.drop_table("drafts", schema="sales")
    op.drop_index(
        op.f("ix_conversations_workspace_id_company_id"), table_name="conversations", schema="sales"
    )
    op.drop_table("conversations", schema="sales")
    op.drop_table("contact_permissions", schema="sales")
    op.drop_index(
        "uq_opportunities_active_pair",
        table_name="opportunities",
        schema="sales",
        postgresql_where=sa.text(
            "status NOT IN ('not_interested','won','lost','archived','disqualified')"
        ),
    )
    op.drop_index(
        op.f("ix_opportunities_workspace_id_status_next_action_at"),
        table_name="opportunities",
        schema="sales",
    )
    op.drop_table("opportunities", schema="sales")
    op.drop_index(op.f("ix_evidence_company_id"), table_name="evidence", schema="sales")
    op.drop_table("evidence", schema="sales")
    op.drop_index(
        op.f("ix_usage_ledger_workspace_id_occurred_at"), table_name="usage_ledger", schema="sales"
    )
    op.drop_table("usage_ledger", schema="sales")
    op.drop_index(op.f("ix_run_events_run_id_occurred_at"), table_name="run_events", schema="sales")
    op.drop_table("run_events", schema="sales")
    op.drop_index(
        op.f("ix_budget_reservations_workspace_id_status"),
        table_name="budget_reservations",
        schema="sales",
    )
    op.drop_table("budget_reservations", schema="sales")
    op.drop_table("telegram_link_codes", schema="sales")
    op.drop_table("telegram_callbacks", schema="sales")
    op.drop_index(op.f("ix_runs_workspace_id"), table_name="runs", schema="sales")
    op.drop_table("runs", schema="sales")
    op.drop_table("integrations", schema="sales")
    op.drop_table("integration_secrets", schema="sales")
    op.drop_table("inbound_events", schema="sales")
    op.drop_table("digests", schema="sales")
    op.drop_table("daily_quotas", schema="sales")
    # ### end Alembic commands ###
    op.drop_constraint(op.f("uq_contacts_workspace_id_id"), "contacts", schema="sales", type_="unique")
